### ISSUE TITLE
Import error , No Module named redis 

### ISSUE THREAD

**Issue by timtensor** [Ferrnya/Lifting-from-the-Deep-release-for-video#1]
Hi I was trying to run your implementation on python3.6 and i seem to get the following error . Do you know why ?
Sorry my mistake ,  i close this issue for now 
```
 python3.6 video_local.py 
Traceback (most recent call last):
  File "video_local.py", line 21, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'

```

**Comment by timtensor** [comment]
Actually i am sorry , i installed the package but i have the following error 

```
`  File "video_local.py", line 156, in <module>
    sys.exit(main())
  File "video_local.py", line 46, in main
    db="xxxx", charset='utf8')
  File "/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File ".local/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "ocal/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'xxxx' ([Errno -2] Name or service not known)")
`
```
